version: "3"
services:
  # php
  php-nginx-alpine:
    container_name: 'php-nginx-alpine'
    build: .
    volumes:
      - './html:/usr/share/nginx/html'
    ports:
      - '80:80'
      - '9000:9000'
    tty: true
    links:
      - mysql-server
  # DB
  mysql-server:
    container_name: mysql-server
    image: mysql:5.6
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
